// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-ODDJlU-KSGEM1b-lwvlgeI3WiiNeBo',
    appId: '1:606456156488:android:a8fcd520f1c5ea1016a37d',
    messagingSenderId: '606456156488',
    projectId: 'parla0',
    databaseURL: 'https://parla0-default-rtdb.firebaseio.com',
    storageBucket: 'parla0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGbSuEcK08k4pkFCa9-GxMUhbsmtHhdY',
    appId: '1:606456156488:ios:6384f79d079c307616a37d',
    messagingSenderId: '606456156488',
    projectId: 'parla0',
    databaseURL: 'https://parla0-default-rtdb.firebaseio.com',
    storageBucket: 'parla0.firebasestorage.app',
    iosClientId: '606456156488-lnsbnkia37k1bh4tv9civrvai49e3ll9.apps.googleusercontent.com',
    iosBundleId: 'me.ritom.parla',
  );
}
