import 'package:easy_overlay/easy_overlay.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:forui/forui.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:parla/riverpod/auth_provider.dart';
import 'package:parla/riverpod/theme_notifier.dart';
import 'package:parla/screens/auth/login_screen.dart';
import 'package:parla/screens/main_navigation.dart';
import 'package:parla/services/presence.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(ProviderScope(child: const Application()));
}

class Application extends ConsumerWidget {
  const Application({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = ref.watch(themeProvider);

    return FTheme(
      data: theme, // Forui-native theme application
      child: MaterialApp(
        supportedLocales: FLocalizations.supportedLocales,
        localizationsDelegates: const [
          ...FLocalizations.localizationsDelegates,
        ],
        debugShowCheckedModeBanner: false,
        theme: theme.toApproximateMaterialTheme(),
        builder: (context, child) {
          return FAnimatedTheme(
            data: theme,
            child: EasyOverlay.init()!(context, child),
          );
        },
        home: const FScaffold(child: AppRoot()),
      ),
    );
  }
}

class AppRoot extends ConsumerWidget {
  const AppRoot({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final user = ref.watch(authProvider);
    if (user != null) {
      ref.watch(presenceServiceProvider);
      return MainNavigation();
    } else {
      return LoginScreen();
    }
  }
}
